EXT_CC=gcc
EXT_LD=$(EXT_CC)

LIBMIKMOD_CONFIG=libmikmod-config
LIBMIKMOD_CFLAGS=$(shell $(LIBMIKMOD_CONFIG) --cflags)
LIBMIKMOD_LIBS  =$(shell $(LIBMIKMOD_CONFIG) --libs)

MIKMOD_CFLAGS=-Wall -g $(LIBMIKMOD_CFLAGS)
MIKMOD_LDFLAGS=$(LIBMIKMOD_LIBS)

%.o: %.c %.h
	$(EXT_CC) $(MIKMOD_CFLAGS) -c $<